CONTIKI=../contiki
TARGET=iotlab-m3

#CFLAGS += -DWITH_NON_STORING=1

ifeq ($(realpath $(CONTIKI)),)
$(shell git clone https://github.com/iot-lab/contiki $(CONTIKI))
$(shell git clone https://github.com/iot-lab/openlab $(CONTIKI)/platform/openlab/git)
endif
