CONTIKI=../contiki
TARGET=iotlab-m3

CONTIKI_WITH_IPV6 = 1

CFLAGS += -DWITH_NON_STORING=1

MODULES += core/net/mac/tsch
CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"
SMALL = 1

ifeq ($(realpath $(CONTIKI)),)
$(shell git clone https://github.com/iot-lab/contiki $(CONTIKI))
$(shell git clone https://github.com/iot-lab/openlab $(CONTIKI)/platform/openlab/git)
endif
